### ISSUE TITLE
Use pdisk/info endpoint for PDisk page

### ISSUE THREAD

**Issue by artemmufazalov** [ydb-platform/ydb-embedded-ui#872]
Based on https://github.com/ydb-platform/ydb/pull/5195

**Comment by adameat** [comment]
![image](https://github.com/ydb-platform/ydb-embedded-ui/assets/34044711/6b3315d7-b758-44eb-808c-8ae12ef8edcf)


pdisk properties:
* node_id - pdisk_id (I expect it to be in the header)
* somewhere on the top, where Restart button is - DecomissionStatus (DecommitStatus)
* BSC/Type, Path, Guid, SerialNumber
* BSC/StatusV2, State, Device, Realtime
* Space: AvailableSize / TotalSize (as one progress bar)
* Slots: BSC/NumActiveSlots / BSC/ExpectedSlotCount (as one progress bar)
* Log: LogUsedSize/LogTotalSize (as one progress bar)  SystemSize (it would be nice to show it on one row)

it would be also nice to show BSC/SharedWithOs attribute as a label. it's only important when it's true. so, it could be absent otherwise.
